using System;

namespace canopyws.Models
{
    public class EmployeeModel
    {
        public string username { get; set; }
        public string password { get; set; }
        public string grant_type { get; set; }
        public string employeeUserId { get; set; }
        public string personalFirstName { get; set; }
        public string personalMiddleName { get; set; }
        public string personalMiddleInitial { get; set; }
        public string personalLastName { get; set; }
        public string personalSuffixName { get; set; }
        public string personalSuffixDescription { get; set; }
        public string personalSsn { get; set; }
        public string personalBirthday { get; set;}
                                        "personalHomeStreet1",
                                        "personalHomeStreet2",
                                        "personalHomeCity",
                                        "personalHomeState",
                                        "personalHomeZipCode",
                                        "personalHomeCountry",
                                        "personalSex",
                                        "personalMaritalStatus",
                                        "personalRaceEthnicity",
                                        "personalHomePhoneAreaCode",
                                        "personalHomePhoneNumber",
                                        "personalCellPhoneAreaCode",
                                        "personalCellPhoneNumber",
                                        "personalIsSmoker",
                                        "personalIsDisabledVet",
                                        "personalIsVietnamEraVet",
                                        "personalDriversLicenseNumber",
                                        "personalDriversLicenseExpiration",
                                        "personalDriversLicenseState",
                                        "personalDriversLicenseCountry",
                                        "personalForeignCitizen",
                                        "jobClassificationNumber",
                                        "jobClassificationTitle",
                                        "jobClassificationDescription",
                                        "positionNumber",
                                        "positionName",
                                        "positionCc1LocationName",
                                        "positionCc1LocationDescription",
                                        "positionCc2DepartmentName",
                                        "positionCc2DepartmentDescription",
                                        "positionCc3DivisionName",
                                        "positionCc3DivisionDescription",
                                        "positionFlsaName",
                                        "positionFlsaDescription",
                                        "positionWorkersCompName",
                                        "positionWorkersCompDescription",
                                        "employmentNumber",
                                        "employmentStatus",
                                        "employmentTypeCode",
                                        "employmentTypeDesc",
                                        "employmentHireDate",
                                        "employmentOriginalHireDate",
                                        "employmentSeniorityDate",
                                        "employmentTerminationDate",
                                        "employmentEmail",
                                        "employmentReportsToPersonalFirstName",
                                        "employmentReportsToPersonalMiddleName",
                                        "employmentReportsToPersonalMiddleInitial",
                                        "employmentReportsToPersonalLastName",
                                        "employmentTerminationReasonName",
                                        "employmentTerminationReasonDescription",
                                        "employmentIsVeteran",
                                        "primaryEmergencyContactName",
                                        "primaryEmergencyContactRelationship",
                                        "primaryEmergencyContactAddress1",
                                        "primaryEmergencyContactAddress2",
                                        "primaryEmergencyContactCity",
                                        "primaryEmergencyContactState",
                                        "primaryEmergencyContactCountry",
                                        "primaryEmergencyContactZip",
                                        "primaryEmergencyContactHomePhoneAreaCode",
                                        "primaryEmergencyContactHomePhoneNumber",
                                        "primaryEmergencyContactWorkPhoneAreaCode",
                                        "primaryEmergencyContactWorkPhoneNumber",
                                        "primaryEmergencyContactWorkPhoneExt",
                                        "primaryEmergencyContactCellPhoneAreaCode",
                                        "primaryEmergencyContactCellPhoneNumber",
                                        "primaryEmergencyContactHomeEmail",
                                        "primaryEmergencyContactWorkEmail",
                                        "taxWorkState",
                                        "taxResidenceState",
                                        "taxFederalMarriedStatusName",
                                        "taxFederalMarriedStatusCode",
                                        "taxFederalExtra",
                                        "taxFederalExtraIsPercent",
                                        "taxFederalDependents",
                                        "taxStateMarriedStatusName",
                                        "taxStateMarriedStatusCode",
                                        "taxStateExtra",
                                        "taxStateExtraIsPercent",
                                        "taxStateDependents",
                                        "taxLocalMarriedStatusName",
                                        "taxLocalMarriedStatusCode",
                                        "taxLocalExtra",
                                        "taxLocalExtraIsPercen",
                                        "payEffectiveDate",
                                        "payChangeReasonCode",
                                        "payChangeReasonDescription",
                                        "payTypeCode",
                                        "payTypeDescription",
                                        "payFrequencyCode",
                                        "payFrequencyDescription",
                                        "payStandardHoursPerPayPeriod",
                                        "payAnnualized",
                                        "payPerPeriod",
                                        "payHourly",
                                        "payPayCodeName",
                                        "payPayCodeDescription",
                                        "payPayStatusName",
                                        "payPayStatusDescription",
                                        "payrollGroupName",
                                        "payrollGroupDescription"

    }
}
